# Generated by Django 5.1.4 on 2025-01-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('insta_url', models.CharField(max_length=1000)),
                ('linkedin_url', models.CharField(max_length=1000)),
                ('youtube_url', models.CharField(max_length=1000)),
                ('theme', models.CharField(max_length=1000)),
                ('link_status', models.BooleanField(default=False)),
            ],
        ),
    ]
