# Generated by Django 5.1.5 on 2025-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_linkclick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkClick',
        ),
    ]
