# Generated by Django 5.1.5 on 2025-01-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_linkclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('link_type', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
    ]
