# Generated by Django 5.1.5 on 2025-01-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_linkclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkclick',
            name='visitor_ip',
        ),
    ]
